TEST_SPLIT: 0.1
VALIDATION_SPLIT: 0.2
AUGMENTATION: True
EARLY_STOPPING: True
IMAGE_SIZE: [224, 224, 3] # requested by MobileNet
BATCH_SIZE: 64
INCLUDE_TOP: False
EPOCHS: 10
NUM_CLASSES: 5
WEIGHTS: imagenet
LEARNING_RATE: 0.01